"""drop success criteria tables

Revision ID: 20240722_drop_success_criteria
Revises: 20240621_recreate_success_criteria_requirements
Create Date: 2024-07-22 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20240722_drop_success_criteria'
down_revision = '20240621_recreate_success_criteria_requirements'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('success_criteria_requirements')
    op.drop_table('success_criteria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('success_criteria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('shared_with', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='success_criteria_pkey')
    )
    op.create_table('success_criteria_requirements',
    sa.Column('success_criteria_id', sa.INTEGER(), sa.ForeignKey('success_criteria.id', ondelete='CASCADE'), autoincrement=False, nullable=False),
    sa.Column('requirement_id', sa.INTEGER(), sa.ForeignKey('requirements.id', ondelete='CASCADE'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('success_criteria_id', 'requirement_id', name='success_criteria_requirements_pkey')
    )
    # ### end Alembic commands ### 