apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: pov-platform
spec:
  limits:
  - default:
      cpu: 250m
      memory: 256Mi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container 